kind: Pod
apiVersion: v1
metadata:
  name: pod-config
spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: course
        valueFrom: 
          configMapKeyRef:
            name:  config-map
            key: course

      - name:  duration
        valueFrom: 
          configMapKeyRef:
            name:  config-map   
            key:   duration        
          

          


