apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - ConfigMapRef:
        name: narendra.shop
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:
    #       name: narendra.shop
    #       key: course
    # - name: trainer
    #   valueFrom:
    #     configMapKeyRef:
    #       name: narendra.shop
    #       key: trainer
          
