apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx
  labels:
    app: nginx
    tier: frontend
  spec:
    replicas:3
    selector:
      matchLabels:
        tier: frontend
        apps: nginx

    template:
      metadata:
        labels:
          tier: frontend
          apps: nginx
          project: some-project
      spec:
        containers:
        - name: nginx
          image: nginx    


