kind: Deployment
apiVersion: apps/v1
metadata:
#deployment related labels
  name: nginx 
  labels: 
    app: nginx
    purpose: deployment
    tier: web 
  spec:
    replicas: 3
    selector: 
      matchLabels:
        app: nginx 
        tier: web 
        project: test-project
    template:
      metadata:
        labels:
          app: nginx
          tier: web 
          project: test-project 
          extra-key: extra-value
      spec:
        containers:
        - name: nginx 
          image: nginx 
                    
