apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  #deployment related labels
  labels:
    app: nginx 
    purpose: deployment
    tier: web
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginx 
      purpose: deployment
      tier: web
    #pod definition        
  template:      
    metadata:
      labels:
        app: nginx 
        purpose: deployment
        tier: web    
        extralabel: somevalue
    spec:
      containers:
      - name: nginx 
        image: nginx:stable-perl

