apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    component: mysql
    project: deployment
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: deployment
      tier: db
  template:
    metadata:
      labels:
        component: mysql
        project: deployment
        tier: db
    spec:
      containers:
      - name: mysql
        image: narendranreddy/mysql:v1.0
