apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
  tolerations:
  - key: "project"
    operator: "Equal"
    value: "expense"
    effect: "NoSchedule"
    # kubectl taint nodes ip-192-168-8-248.ec2.internal 
    #project=expense:NoSchedule
  - key: "Project"
    operator: "Exists"
    effect: "NoSchedule"  