apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
  nodeSelector:
    project: expense  
  tolerations:
  - key: "project"
    operator: "Equal"
    effect: "NoSchedule"
    value: "expense"
  - key: "project"
    operator: "Exists"
    effect: "NoSchedule"

