apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd            
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "project"
    operator: "Equal"
    effect: "NoSchedule"    
    value: "expense"
  - key: "project"
    operator: "Exists"
    effect: "NoSchedule"    
 
    
